name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [22]
                environment: [MONGO_URI]

        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install backend dependencies
          working-directory: ./backend
          run: |
            npm install --global yarn
            yarn --version
            yarn install

        - name: Install frontend dependencies
          working-directory: ./frontend
          run: |
            df -h
            sudo rm -rf ./build
            yarn install
            yarn build

        - run: npm ci

        - run: |
            cd ./backend
            touch .env
            echo "${{ secrets.PROD }}" > .env

        - run: pm2 start all
        - run: pm2 restart all